services:
  - type: web
    runtime: docker
    name: wedding-api
    plan: free
    region: frankfurt
    dockerfilePath: ./backend/Dockerfile.prod
    dockerContext: ./backend
    dockerCommand: npm run start:prod
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false

  - type: web
    runtime: docker
    name: wedding-web
    plan: free
    region: frankfurt
    dockerfilePath: ./frontend/Dockerfile.prod
    dockerContext: ./frontend
    healthCheckPath: /health
    autoDeployTrigger: commit
    domains:
      - ozgefatihdugun.tr
    envVars:
      - key: BACKEND_SCHEME
        value: https
      - key: BACKEND_HOST
        fromService:
          name: wedding-api
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: BACKEND_PORT
        value: 443
      - key: FRONTEND_PUBLIC_URL
        value: https://ozgefatihdugun.tr
